version: '3'

services:
  jekyll:
    image: thesnwmn/jekyll
    volumes:
      - .:/site
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - '4000:4000'
    command: bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000
